In [4]:
import numpy as np

# 创建数组

## 一维数组

In [10]:
array_dimension_1=np.array([1,2,3])
array_dimension_1

array([1, 2, 3])

## 二维数组

In [11]:
array_dimension_2=np.array([[1,2,3],[4,5,6]])
array_dimension_2

array([[1, 2, 3],
       [4, 5, 6]])

## 全零数组

In [ ]:
array_zeros=np.zeros(shape=(3,3))
array_zeros

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

## 全一数组

In [15]:
array_ones=np.ones(shape=(2,2))
array_ones

array([[1., 1.],
       [1., 1.]])

## 全空数组

In [ ]:
array_empty=np.empty(shape=(3,3))
array_empty
#无限接近于 0，但不是 0

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

## 连续序列数组

In [ ]:
#np.arange(start,stop,step)  [start,stop)
array_arange=np.arange(0,10,2)
array_arange

array([0, 2, 4, 6, 8])

## 连续间隔数组

In [ ]:
#线性等分向量 linear space , [start,stop]
array_linspace=np.linspace(1,10,20)
array_linspace

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

## np.random模块

### rand,随机的[0,1)数据

In [26]:
np.random.rand(3,3)

array([[0.37801401, 0.03656905, 0.83014743],
       [0.37181179, 0.23759523, 0.19171588],
       [0.20199086, 0.68651151, 0.78429479]])

### randn,标准正态分布

In [27]:
np.random.randn(4,2)

array([[-0.07953582, -0.59245071],
       [-0.30592893,  0.1780207 ],
       [ 0.32450045, -0.49403173],
       [-1.00940893, -0.28369099]])

### randint,随机整数

In [33]:
#randint(low,high=None,size=None.dtype="l")
#如果没有high,默认返回[0,low)
np.random.randint(3,high=10,size=4)

array([5, 4, 6, 9])

### [0,1)的浮点数

In [ ]:
np.random.random_sample(size=None)

0.061618004495289536

In [37]:
np.random.random(size=(2,2))

array([[0.23217473, 0.2472444 ],
       [0.21287799, 0.29809904]])

In [38]:
np.random.ranf()

0.05571353408418844

In [39]:
np.random.sample()

0.7616533285337098

### choice给定数组生成随机数

In [40]:
#choice(a,size=None,replace=None,p=None)
np.random.choice(5,3)

array([4, 4, 4])

### seed随机可预测

In [44]:
np.random.seed(12)
np.random.randn(4)

array([ 0.47298583, -0.68142588,  0.2424395 , -1.70073563])

In [43]:
np.random.seed(12)
np.random.randn(4)

array([ 0.47298583, -0.68142588,  0.2424395 , -1.70073563])

## 改变数组的形状

In [50]:
array_reshape=np.array([[1,2,3],[4,5,7]])
array_reshape.shape,array_reshape.reshape((3,2))

((2, 3),
 array([[1, 2],
        [3, 4],
        [5, 7]]))

## 数组转置

In [52]:
array_t=np.arange(0,10).reshape(2,5)
array_t

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [53]:
array_t.T

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

## 数组属性 

In [57]:
array_attribute=np.array([[1,2,3],[4,5,6]])

In [58]:
array_attribute.ndim

2

In [59]:
array_attribute.shape

(2, 3)

In [60]:
array_attribute.size

6

In [61]:
array_attribute.dtype

dtype('int64')

# 数组运算

- 平均数mean
- 中位数median
- 标准差std
- 方差var
- 最小值min
- 最大值max
- 元素和sum
- 元素乘积prod
- 元素累计和cumsum

In [62]:
array_calculate_1=np.array([1,2,3])
array_calculate_2=np.array([4,5,6])
array_calculate_1+array_calculate_2

array([5, 7, 9])

In [63]:
array_calculate_1*array_calculate_2

array([ 4, 10, 18])

In [69]:
array_mean=np.arange(0,12).reshape(3,4)
np.mean(array_mean,axis=0),np.mean(array_mean,axis=1)

(array([4., 5., 6., 7.]), array([1.5, 5.5, 9.5]))

array([4., 5., 6., 7.])

# 数组切片